[package]
name    = "xrla-difftest"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "xrla-difftest"
path = "src/main.rs"

[dependencies]
anyhow      = { workspace = true }
clap        = { workspace = true }
rusqlite    = { version = "0.31", features = ["bundled"] }
xrla-common = { path = "../xrla-common" }
xrla-index  = { path = "../xrla-index" }
